### ISSUE TITLE
Plugin issues...

### ISSUE THREAD

**Issue by FurryOfficial** [svenar-nl/PowerRanks#32]
**I'm not a dummy, so I've checked these**
- [x] I am not using any other permission management plugin
- [x] I use the latest available version of PowerRanks
- [x] I am a human

**Describe the bug**
Sometimes PR loses it ranks and permission, i tried to reload/unload the plugin but it wont help.

**To Reproduce**
i dunno :L

**Expected behavior**
Not happen this again
**Screenshots**
https://cdn.discordapp.com/attachments/710835410070274049/848470043847426048/unknown.png

**Logs**
[08:55:53 WARN]: java.lang.NullPointerException
[08:55:53 WARN]: java.lang.NullPointerException
[08:55:54 WARN]: [PowerRanks] Task #31659930 for PowerRanks v1.9.9R3 generated an exception
java.lang.NullPointerException: null
        at nl.svenar.PowerRanks.PowerRanks.updatePlaytime(PowerRanks.java:952) ~[?:?]
        at nl.svenar.PowerRanks.PowerRanks$3.run(PowerRanks.java:355) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-634]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-634]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-634]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-634]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-634]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-634]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-634]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[08:55:54 WARN]: java.lang.NullPointerException
[08:55:55 WARN]: java.lang.NullPointerException

**Desktop (please complete the following information):**
 - OS: Linux
 - Server type paper 1.16.5
 - Minecraft Version 1.16.5
 - PowerRanks version 1.9.9R3

**Additional context**

**Comment by greatericontop** [comment]
Can you send the ranks.yml, config.yml, and list of plugins? 1.9.9R2/3 also is a bit buggy so see if the same issue arises in 1.9.8
